### ISSUE TITLE
Industry Job -> Outputlocation ID is long in EveStandard, but int64 in ESI

### ISSUE THREAD

**Issue by soomon** [gehnster/EVEStandard#113]
Hi,

I noticed that according to the ESI https://esi.evetech.net/ui/#/Industry/get_characters_character_id_industry_jobs, OutputlocationId is an int64, but you have it as a long https://github.com/gehnster/EVEStandard/blob/master/EVEStandard/Models/IndustryJob.cs

I am a noob, so there's a good chance I am missing something. Would you please let me know what? :D
Thanks!

**Comment by scott-downey** [comment]
Hi @soomon,
[long](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types) is the .Net alias for Int64.
I hope this clears things up for you.
Thanks

**Comment by soomon** [comment]
Well that is embarrasing XD
thanks :)

**Comment by gehnster** [comment]
Glad you found your answer! :)
