### ISSUE TITLE
SSOv2 constructor throws exception when clientSecret is null or empty

### ISSUE THREAD

**Issue by ebeisecker** [gehnster/EVEStandard#134]
Since Eve Application Secret Key's are not used when using the [PKCE protocol](https://docs.esi.evetech.net/docs/sso/native_sso_flow.html#overview-of-oauth-20-flow-for-native-applications) for authentication, it seems like the SSOv2 class should not throw an ArgumentNullException if a Secret Key is not provided. 

Repro steps
`var sso = new SSOv2(DataSource.Tranquility, "http://localhost/callback", "MyEVEAppClientId", null);`

**Comment by gehnster** [comment]
According to the document you reference, which has this section ```Note on security: the access token should also be stored securely but if it were to get leaked it can only be used for as long as is left of its 20 minute lifetime. If your refresh token gets leaked it can only be invalidated by you, the application developer, by [revoking it](https://docs.esi.evetech.net/docs/sso/revoking_refresh_tokens.html). If you know your refresh token has been leaked you must revoke it.``` and mentions revoking your token you do need the client secret to revoke tokens for EVE SSOv2.

**Comment by ebeisecker** [comment]
I would need to use my Application's Secrete key to revoke tokens for EVE SSOv2. However, since I'm building a Desktop application I'm trying to comply with this statement in the EVE SSO Documentation 
```In the PCKE protocol, a code challenge is used instead of basic authentication to allow your application to ship without its secret key. The reason for this being to protect malicious actors from being able to decompile your programs and retrieve the secret key. A more detailed explanation of the kind of attacks this protects against can be found in [RFC 7636](https://tools.ietf.org/html/rfc7636#section-1)```

Since someone who is using my application would have the ability to potentially decompile my application, I would not bundle my Application's Secret key with my application. That is why I am using the PKCE protocol for authentication. Since I don't have a secret key in my app, it seems weird that the `SSOv2` object should throw an exception if I'm trying to create an instance of that object without a secret key.

**Comment by gehnster** [comment]
Talked to some other devs about this, looks like the revoke endpoint is broken and has been since 2018 so I'll make it an optional parameter. Update with change should be going to NuGet shortly.
