### ISSUE TITLE
Add Dogma

### ISSUE THREAD

**Issue by gehnster** [gehnster/EVEStandard#19]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/dogma/index.html

**Comment by scott-downey** [comment]
There is currently a Dogma module in EVEStandardAPI that does implement the [calls](https://esi.evetech.net/ui/#/Dogma), is there anything further that needs to be done to close this off?

**Comment by gehnster** [comment]
I don't remember anymore, it's been too long. I can just close it though.
