### ISSUE TITLE
Update package to .NET Standard 2.1

### ISSUE THREAD

**Issue by gehnster** [gehnster/EVEStandard#23]
Update the package and dependencies to .NET Standard 2.1

**Comment by gehnster** [comment]
.NET Standard 2.1 doesn't look to be coming anytime soon so will have to put this on the back burner for a while.

**Comment by octave-syndicate** [comment]
.NET Standard 2.1 has been released in the interim and we're on to .NET 5.0. I'm happy to submit PRs for either of these along with package upgrades.

**Comment by gehnster** [comment]
> .NET Standard 2.1 has been released in the interim and we're on to .NET 5.0. I'm happy to submit PRs for either of these along with package upgrades.

Is there something in .Net Standard 2.1 that you need? I ask because if I raise the .net standard version it will raise the minimum version of the .NET frameworks. Reference page for what I'm talking about: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by octave-syndicate** [comment]
There's nothing in particular I need. I've built my own versions of NETStandard and NETStandard against .net 5 to take advantage of the performance advantages associated with the new version but it's completely reasonable to leave the nuget package and the project itself on a previous version for the sake of greater compatibility.

**Comment by gehnster** [comment]
There shouldn't be a problem using the evestandard package at v 2.0 within a .net 5 application, should work fine.
