### ISSUE TITLE
AuthDTO awkward to use

### ISSUE THREAD

**Issue by lstyles** [gehnster/EVEStandard#27]
Probably an low priority improvement, but the AuthDTO model is too complex and difficult to compose between requests. It's easy to use in the same request as the callback but composing it in other requests from saved token is awkward, especially that most calls just a couple of properties contained in the DTO.

**Comment by gehnster** [comment]
Yep, this is actually something I've been thinking about changing for 2.0 of the library, but I can honestly see reasons why I also like it but would maybe just want to trim it down. I'm always open to a discussion and pull requests on what you think could be a better approach.

**Comment by lstyles** [comment]
I think that a POCO that's only holding properties required would work better. Alternatively, individual API calls could have overloads that take the required parameters only. Then, calls to the API methods that take AuthDTO could just extract required information from the DTO and call the method that requires simple params.

**Comment by gehnster** [comment]
Fixed up a bit in #32
