### ISSUE TITLE
GetStationInfoV2Async Throws Exception

### ISSUE THREAD

**Issue by EFJO** [gehnster/EVEStandard#57]
Calling this method results in an exception similar to the following: "Error converting value "bounty-missions" to type 'EVEStandard.Enumerations.ServicesEnum'." 

It doesn't seem like the services returned from ESI are mapping to the enumeration, this might be complicated by the hyphens included in the response.

**Comment by gehnster** [comment]
Thanks, we'll take a look.

**Comment by EFJO** [comment]
I may have fixed it, just testing now.

**Comment by EFJO** [comment]
Submitted #58. I apologise if I did anything wrong this would be my first pull request :)

**Comment by gehnster** [comment]
Thanks for the PR! Looks good so far. I'll do a couple tests myself, as the other contributor to review the change as well and then hopefully get a new NuGet package released Monday (USTZ)

**Comment by gehnster** [comment]
This has been resolved in PR #58 Thanks for the PR!
