### ISSUE TITLE
Wrong URL in Wallet.GetCorporationWalletJournalV3Async

### ISSUE THREAD

**Issue by notepid** [gehnster/EVEStandard#61]
`var responseModel = await GetAsync($"/v3/corporations/{corpId}/wallet/{division}/journal/", auth, ifNoneMatch, queryParameters);`

should be

`var responseModel = await GetAsync($"/v3/corporations/{corpId}/wallets/{division}/journal/", auth, ifNoneMatch, queryParameters);`

(Missing an s in wallets)

Same for GetCorporationWalletTransactionsV1Async() and this should probably be renamed to V3 :)

**Comment by gehnster** [comment]
Sorry for the delayed response, I've been on vacation for the last five days. I'll take a look at get something pushed out.

**Comment by gehnster** [comment]
url fix applied in PR #62
