### ISSUE TITLE
The Auth callback helper replacement

### ISSUE THREAD

**Issue by nvpetrov** [gehnster/EVEStandard#71]
I had problems the helper not starting or not able to register the callback protocol due  to permissions.

i think that you can use async task, which invokes an async httplistener just before starting the browser and await it to finish after the user submits the callback.

an await.whenany with task.delay could be used to continue operation after some timeout in order not to block the app if something goes wrong with user submitting data

I will be able to post my code tomorrow if you want to check it out.

**Comment by lstyles** [comment]
Is this for a desktop app? 

I'd love to see it.

**Comment by Mortalitis** [comment]
+1 if it is for desktop apps, only thing I am struggling with. Having to use manual method for 'closing the loop'.

**Comment by nvpetrov** [comment]
Winforms. VB. NET
I am at a concert atm, will post the code tomorrow.

**Comment by lstyles** [comment]
I'm not very good at reading VB.NET so it will take me a while to get my head around it.

**Comment by Mortalitis** [comment]
Trying to get my head around it and integrate into my test app. I already generated the URL myself so I only need the callback listener to grab the auth code.

**Comment by lstyles** [comment]
Apologies for taking so long to respond. I think I understand what you are trying to do but I'm not sure I know how to help. It does seem like an issue with a library, but instead a question about either starting a http listener or registering a protocol handler.
