### ISSUE TITLE
Automatic Decompression

### ISSUE THREAD

**Issue by gehnster** [gehnster/EVEStandard#94]
Change decompression for http client to be automatic. Change it for all http clients.

**Comment by wjkuijpers** [comment]
I tried using your library and ran into that problem. It's an easy fix.

            http = new HttpClient(new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate });
            http.DefaultRequestHeaders.Add("User-Agent", HttpUtility.UrlEncode(userAgent));
            http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            http.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
            http.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate"));
            http.Timeout = timeOut;
